services:
  web:
    build: ./detector
    command: gunicorn detector.wsgi:application --bind 0.0.0.0:8000
#    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./detector/:/detector/
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}
  nginx:
    build: ./nginx
    volumes:
      - ./detector/:/detector/
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data: