# Generated by Django 5.0.2 on 2024-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('ERC-20', 'Erc20'), ('ERC-721', 'Erc721')], default='ERC-20', max_length=20)),
                ('contract_address', models.CharField(max_length=100)),
                ('source_code', models.TextField()),
                ('is_correct', models.BooleanField(null=True)),
                ('version', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
            ],
        ),
    ]
